name: Publish Snapshot

on:
    push:
        branches:
            - master
            - ci/*

jobs:
    check-if-snapshot:
        runs-on: ubuntu-latest
        outputs:
            is_snapshot: ${{ steps.set-if-snapshot.outputs.snapshot }}
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: ${{ github.ref }}

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Get Version
                run: ./gradlew properties -q | grep "^version:" | awk '{printf "PROJECT_VERSION=" $2}' >> $GITHUB_ENV

            -   name: Enable if Snapshot
                id: set-if-snapshot
                run: echo "::set-output name=snapshot::true"
                if: endsWith(env.PROJECT_VERSION, 'SNAPSHOT')

    publish-gcp-artifacts:
        needs: check-if-snapshot
        if: ${{ needs.check-if-snapshot.outputs.is_snapshot }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: ${{ github.ref }}

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Check
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: check

            -   name: Setup GCP
                uses: google-github-actions/setup-gcloud@master
                with:
                    project_id: ${{ secrets.GCP_PROJECT_ID }}
                    service_account_key: ${{ secrets.GCP_ARTIFACTS_KEY }}
                    export_default_credentials: true

            -   name: Upload to GCP
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: publish
                env:
                    ENABLE_GCP: true
