name: Publish Snapshot

on:
    push:
        branches:
            - master
            - ci/*

jobs:
    check-if-snapshot:
        runs-on: ubuntu-latest
        outputs:
            is_snapshot: ${{ steps.set-if-snapshot.outputs.snapshot }}
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: ${{ github.ref }}

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Get Version
                run: ./gradlew properties -q | grep "^version:" | awk '{printf "PROJECT_VERSION=" $2}' >> $GITHUB_ENV

            -   name: Enable if Snapshot
                id: set-if-snapshot
                run: echo "::set-output name=snapshot::true"
                if: endsWith(env.PROJECT_VERSION, 'SNAPSHOT_NOT')

    debug:
        needs: check-if-snapshot
        runs-on: ubuntu-latest

        steps:
            -   name: Show var
                run: echo ${{ needs.check-if-snapshot.outputs.is_snapshot }}

            -   name: Show vars
                run: echo ${{ needs.check-if-snapshot.outputs }}

            -   name: Run if
                run: echo "ok"
                if: ${{ needs.check-if-snapshot.outputs.is_snapshot }}

    publish-gcp-artifacts:
        needs: check-if-snapshot
        if: ${{ needs.check-if-snapshot.outputs.is_snapshot }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: ${{ github.ref }}

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 11

            -   name: Check
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: check
